### PR TITLE
A collection of small fixes

### PR DESCRIPTION
**Pull request by mortenlj**
I have had my own fork that I applied some fixes to, but now that I found that I needed to update to Python 3 I'd rather use a fork that has seen more maintenance. Since I rely on these fixes in my project, it makes sense to offer them up for inclusion here.

Each commit should be self-contained, and the commit message should explain well enough.

I have not added new unit tests, because I've only extended the original doctests in my fork. If wanted, I can possibly set aside some time to implement the tests as unittests instead.

### CODE REVIEW

**Comment by ccanepa** [comment]
I appreciate the PR, will look at it in these week.

**Comment by ccanepa** [comment]
Hello,
Nice you did a separate commit for each feature.

Commits
- Applied patch to fix Circle intersecting LineSegment2 and related types … -f842470
- Added rotation for Vector2 - 06df005
- determinant operation for Vector2 - efb07ef

are ok and ready to merge; I wrote some unittest for them that I will commit after merge. 

Commit 
- Change formula for angle calculation for Vector2, to faster version

I see a bit of a problem here
- The 'angle' definition in linear algebra is angle = acos(v dot w) / (|v| * |w|)
- If you search for 'vector angle' or similar, most hits will use the acos formula
- The atan2 formula used in the commit is qualitatively different from the acos formula, angle_acos == abs(angle_atan2)

On the other side, the angle_atan2 is more useful in certain cases.

Probably it would be better if 
 - Vector2.angle used the acos formula
 - Another Vector2 method used the atan2 formula. ( I don't think theres a strong conventional name for this angle style, I have seen some call it 'oriented_angle'; maybe Vector2.angle_oriented ?') 

What do you think?

Commit 
- Add clockwise operation to Vector2

I'm 0- for this just because of the top of my head I dont se a use case when (I want to know clockwise or not but I dont need the angle); if I need the angle then the atan2 formula gives me the angle and the sign will tell if it is clockwise or not)

Anyway, if you see an use then I have no problem to merge that commit.

**Comment by mortenlj** [comment]
You are quite right about the change for `angle`. In my own work, I only have use for the oriented variant, but didn't think about the fact that others might be expecting the absoluteness of the result. I'll fix it so the original is kept and my variant is named `angle_oriented` (I think that's a good a name as any).

With regards to the clockwise operation, I use it to find targets in a field of view. But as I was writing up an explanation of how I use it, I realise that I might do it in a different way that doesn't need the clockwise operation, and might even be simpler. I'll revert that commit.

**Comment by ccanepa** [comment]
I'm ready to merge.

It can be done with the usual 'merge' button in github, which left all commits as they are, or after a git rebase -i so that the unwanted changes dont show in history, as seen in https://github.com/euclid3/euclid3/commits/mortenlj-master

- The rebased version looks better in euclid3/euclid3, and will not produce unwanted results in a git bisect
- The rebased version, because it is rewriting history, may complicate / be not suitable to reason about any software you have that used euclid from your repo

I sligtly preffer the rebased one, but have no problem merging the original, let me know your preference.

**Comment by mortenlj** [comment]
I have no problem with rewriting history here, so feel free to rebase and clean it up as you see fit. 🙂

**Comment by ccanepa** [comment]
Thanks, merged and added some tests.

**Pull request closed without merging**
